spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false
    clean-on-validation-error: true
    validate-on-migrate: false
jwt:
  public-key: classpath:app.pub.key
  private-key: classpath:app.key
